// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBawjOoAb66-umUnq5MaZAKXZsWB2DrpU4',
    appId: '1:57733478969:web:aaa9975e215127164eebe8',
    messagingSenderId: '57733478969',
    projectId: 'twitter-3feec',
    authDomain: 'twitter-3feec.firebaseapp.com',
    storageBucket: 'twitter-3feec.appspot.com',
    measurementId: 'G-SSV2G4QPQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXlF7BdrOJqj3MnTVy6kOtTji0UvlvHBI',
    appId: '1:57733478969:android:ca5960199cb7f0c14eebe8',
    messagingSenderId: '57733478969',
    projectId: 'twitter-3feec',
    storageBucket: 'twitter-3feec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALW_kpIIEMxk3NyDW0Aa1tBQ9IL10gMLI',
    appId: '1:57733478969:ios:cf163cea5fa126e94eebe8',
    messagingSenderId: '57733478969',
    projectId: 'twitter-3feec',
    storageBucket: 'twitter-3feec.appspot.com',
    androidClientId: '57733478969-lnv6v1ka5aaamhbia8hiudd248f5fgnq.apps.googleusercontent.com',
    iosClientId: '57733478969-jd9cvdas3orbaq189cseb91al1jdoq3h.apps.googleusercontent.com',
    iosBundleId: 'com.pahuja.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALW_kpIIEMxk3NyDW0Aa1tBQ9IL10gMLI',
    appId: '1:57733478969:ios:cf163cea5fa126e94eebe8',
    messagingSenderId: '57733478969',
    projectId: 'twitter-3feec',
    storageBucket: 'twitter-3feec.appspot.com',
    androidClientId: '57733478969-lnv6v1ka5aaamhbia8hiudd248f5fgnq.apps.googleusercontent.com',
    iosClientId: '57733478969-jd9cvdas3orbaq189cseb91al1jdoq3h.apps.googleusercontent.com',
    iosBundleId: 'com.pahuja.twitterClone',
  );
}
